name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 8.15.1
        uses: actions/setup-node@v1
        with:
          node-version: 18.14.0
      - name: Build and Deploy
        uses: Sundays32/F1InfoApp/F1App/
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BASE_BRANCH: main
          BRANCH: gh-pages
          FOLDER: dist/
          BUILD_SCRIPT: npm install && npm run build -- --prod
